#improve colors
set-option -g default-terminal "tmux-256color"
set-option -a terminal-features 'xterm-256color:RGB'

# reload config
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

set -g default-shell /bin/zsh
set -g prefix ^S
set -g base-index 1

set -g renumber-windows on

set -g detach-on-destroy off
set -s escape-time 0
set -g set-clipboard on 
set -g default-terminal "${TERM}"

# set up vim motions
setw -g mode-keys vi
unbind v
bind v copy-mode

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

bind-key n command-prompt "new-session -s '%%'"
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"

bind-key -r ^H select-window -t :-
bind-key -r ^L select-window -t :+

# test
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @catppuccin_flavor 'frappe'

set -g @catppuccin_window_status_style "rounded"
set -gq @thm_bg_base "#1e1e2e"
set -g @catppuccin_status_background "#{@thm_bg_base}"

# set -g @catppuccin_status_background "default"

# Catppuccin customize status modules styling
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

# Catppuccin customize windows styling
set -g @catppuccin_window_text_color "#{@thm_surface_0}"
set -g @catppuccin_window_number_color "#{@thm_rosewater}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_current_text_color "#{@thm_surface_1}"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"

#FIX: Custome online_status catppuccin status module
# %hidden MODULE_NAME="network"
# set -g "@catppuccin_${MODULE_NAME}_icon" "#{l:#{@online_status_icon}}"
# set -g "@catppuccin_${MODULE_NAME}_color" "#{@thm_pink}"
# set -g "@catppuccin_${MODULE_NAME}_text" "#{l:#{@online_status}}"
# source "~/.config/tmux/plugins/catppuccin/tmux/utils/status_module.conf"

#Config Catppuccin
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'


# Left status bar modules
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -ag status-left "#{E:@catppuccin_status_application}"
# set -ag status-left "#{E:@catppuccin_status_user}"
# set -ag status-left "#{E:@catppuccin_status_directory}"

# Right status bar modules
set -g status-right-length 100
set -g status-right ""
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_battery}"
# set -ag status-right "#{E:@catppuccin_status_date_time}"

set-option -g status-position bottom
set -g status-justify "absolute-centre"

# set -g @continuum-restore 'on'
# set -g @resurrect-strategy-nvim 'session'

# initialize tmux plugin manager (keep this line at the bottom of the file)
run '~/.tmux/plugins/tpm/tpm'
